### ISSUE TITLE
Create a social preview 

### ISSUE THREAD

**Issue by iremide1022** [open-life-science/branding#14]
This issue is for discussing OLS' social previews. We can use this space to clarify what the work looks like and link pull requests to if they are suggested social previews. The final step will be to change the repository's social preview [following GitHub's process](https://help.github.com/en/github/administering-a-repository/customizing-your-repositorys-social-media-preview).
## What's a social preview?
They are like cards giving a sneak preview of what a shared link will lead to. If you paste a link to OLS' GitHub page on Twitter, for example, an image appears. This is the site's social preview. It serves as eye-candy, getting people interested to click and see what the site's about!
## Things to keep in mind
Social previews might look different according to where we share links (for example, Twitter might show a slightly different social preview to Slack).

**Comment by jilaga** [comment]
@yochannah is this the same issue you opened in #4 ?  I made a pull request on #4 and would love your feedback, thank you

**Comment by niyolynate** [comment]
Hello 
I would like to contribute to this Issue

**Comment by niyolynate** [comment]
This is how my social media preview would look like
![phn preview](https://user-images.githubusercontent.com/98440370/195214783-735985ee-78c6-4d49-bf89-48bfd3361f6c.png)
![preview PC](https://user-images.githubusercontent.com/98440370/195214699-2c78e6da-8a37-42ad-a015-d8440ebfc6c0.PNG)

**Comment by iremide1022** [comment]
<img width="640" alt="social preview" src="https://user-images.githubusercontent.com/115456602/195245859-7ca481ec-732b-4c09-8d22-ccdbf82492ff.png">

**Comment by iremide1022** [comment]
![social preview (1)](https://user-images.githubusercontent.com/115456602/195246321-43984f4f-e283-4134-934d-470e6d3e78dd.png)

**Comment by iremide1022** [comment]
This is a social preview i created``

**Comment by Blessing1135** [comment]
Hello, @yochannah my name is Blessing  I would like to work on this project. Thank you.

**Comment by Bisola15** [comment]
Hi @yochannah   I would like to work on this issue

**Comment by Ismael-KG** [comment]
This is a great issue! I do have a few questions, though. It would be great if everyone could help with them:

1. What's a social preview? 
2. Does it look the same wherever a link is shared? (Say, Slack, Twitter.)
3. What other things are important about social media previews?

@iremide1022, as you opened the issue, I wonder if you could edit the opening comment once we have some answers?

That way, as people open the issue, they understand what's being worked on. How does that sound?

**Comment by Bisola15** [comment]
> This is a great issue! I do have a few questions, though. It would be great if everyone could help with them:
> 
> 1. What's a social preview?
> 2. Does it look the same wherever a link is shared? (Say, Slack, Twitter.)
> 3. What other things are important about social media previews?
> 
> @iremide1022, as you opened the issue, I wonder if you could edit the opening comment once we have some answers?
> 
> That way, as people open the issue, they understand what's being worked on. How does that sound?

1. Hi @Ismael-KG A social preview is a pictorial representation of what a link to a brand will look like when shared to other people. For example, If I copied the link to OLs's GitHub site and pasted it to a friend, what would they see.  

2. No, it does not look the same. From my research, Social previews on slack are generally different, they are longer  (with the description running longer) . If I could send a picture... For whatsApp, they are shorter consisting only of a brand logo or a header picture (or not if an image is absent), A title, slight description of the page if there is any and the actual link to the page.
4. Based on other social previews I studies, there was the common theme I listed above. I also noticed that they are clear, not overloaded with information.

If you check the pull request, some social previews has been designed already. 

Thank you so much for helping out!

**Comment by NPDebs** [comment]
> This is a great issue! I do have a few questions, though. It would be great if everyone could help with them:
> 
> 1. What's a social preview? 
> 2. Does it look the same wherever a link is shared? (Say, Slack, Twitter.)
> 3. What other things are important about social media previews?
> 
> @iremide1022, as you opened the issue, I wonder if you could edit the opening comment once we have some answers?
> 
> That way, as people open the issue, they understand what's being worked on. How does that sound?

- **Social previews/cards** offer a "preview" or sample of what a post (or a link) would look like when shared across social media platforms.
They serve as eyecandy, used to convince people that the link is click-worthy.
S.Ps are great for branding, and promote trust/identity. They also mean you don't have to explain what a link you shared contains. 😅


- I don't think they look the same everywhere, seeing as some apps customise previews (especially when content is missing).


- It typically contains a title, short description, a domain name, and a clickable image.

**Comment by Esyteck** [comment]
I will love to work on this issue @yo

**Comment by Ismael-KG** [comment]
Thanks @Bisola15 and @NPDebs! That was very helpful! And everyone else for your interest in working on this. 

@iremide1022, thanks for mentioning you can edit the opening comment! Maybe it can look like this (but feel free to make edits):

```
This issue is for discussing OLS' social previews. We can use this space to clarify what the work looks like and link pull requests to if they are suggested social previews. The final step will be to change the repository's social preview [following GitHub's process](https://help.github.com/en/github/administering-a-repository/customizing-your-repositorys-social-media-preview).
## What's a social preview?
They are like cards giving a sneak preview of what a shared link will lead to. If you paste a link to OLS' GitHub page on Twitter, for example, an image appears. This is the site's social preview. It serves as eye-candy, getting people interested to click and see what the site's about!
## Things to keep in mind
Social previews might look different according to where we share links (for example, Twitter might show a slightly different social preview to Slack).
```

(This text is formatted so you can copy and paste directly, without needing to format any further – I hope this helps and is not confusing! But please ask if it is.)

**Comment by iremide1022** [comment]
@Ismael-KG all you comments are duely noted and I added the changes already, thank you! and yes it really helped

**Comment by caxrii** [comment]
@yochannah @Ismael-KG 
https://github.com/open-life-science/branding/pull/33#issue-1410271041

**Comment by NPDebs** [comment]
> 
```
[https://github.com/open-life-science/branding/pull/33](url)
```

@Caxri7 You may have written your Link wrong. 😃

[Here's the proper link...](https://github.com/open-life-science/branding/pull/33)

**Comment by iremide1022** [comment]
@Ismael-KG is there anything else that needs to be done concerning this issue, please I need a guide 🙏

**Comment by Ismael-KG** [comment]
Good question! Issues serve as a discussion forum – they help get ideas flowing and, hopefully, end in some form of consensus. In this case, we're trying to figure out what the social preview should contain and how it might be formatted to work on different platforms. For the purpose of this issue: have we accomplished this?

And then there's the next step, where pull requests serve as the actual actions following from this issue. There are quite a few pull requests related to this issue. If you want, you can comment on those and help people improve their suggestions!

**Comment by Bisola15** [comment]
> Good question! Issues serve as a discussion forum – they help get ideas flowing and, hopefully, end in some form of consensus. In this case, we're trying to figure out what the social preview should contain and how it might be formatted to work on different platforms. For the purpose of this issue: have we accomplished this?
> 
> And then there's the next step, where pull requests serve as the actual actions following from this issue. There are quite a few pull requests related to this issue. If you want, you can comment on those and help people improve their suggestions!

Thank you @Ismael-KG Seeing as the definition of social preview is similar, I would say we have accomplished it.

Already checked out some. I'll go round to see if there are more 😌

**Comment by Chalcedony219** [comment]
> Good question! Issues serve as a discussion forum – they help get ideas flowing and, hopefully, end in some form of consensus. In this case, we're trying to figure out what the social preview should contain and how it might be formatted to work on different platforms. For the purpose of this issue: have we accomplished this?
> 
> And then there's the next step, where pull requests serve as the actual actions following from this issue. There are quite a few pull requests related to this issue. If you want, you can comment on those and help people improve their suggestions!

Thank you @Ismael-KG 
I think we’re on the same page

**Comment by latifatakin** [comment]
> Good question! Issues serve as a discussion forum – they help get ideas flowing and, hopefully, end in some form of consensus. In this case, we're trying to figure out what the social preview should contain and how it might be formatted to work on different platforms. For the purpose of this issue: have we accomplished this?
> 
> And then there's the next step, where pull requests serve as the actual actions following from this issue. There are quite a few pull requests related to this issue. If you want, you can comment on those and help people improve their suggestions!

@Ismael-KG I believe we have achieved the first purpose which is to figure out what social preview should contain.


For the second part which is the action that follows, we are on track also. I think some suggestions here and there and possibly additional pull requests and then we will achieve our goal.

**Comment by Everythinglayemi** [comment]
This is a social preview I created for a twitter post
<img width="400" alt="SOCIAL Preview" src="https://user-images.githubusercontent.com/103745001/198324505-e437df12-0392-4534-9c02-4462f89ac403.png">

**Comment by kryptosjay** [comment]
hi @Ismael-KG  this is my SOCIAL MEDIA PREVIEW IMAGE
<img width="1200" alt="OPEN LIFE SCI" src="https://user-images.githubusercontent.com/26121833/199868605-3d51eee9-05c0-43fa-ac08-64214e2ce331.png">
![OLS](https://user-images.githubusercontent.com/26121833/199972551-312415f2-4404-4119-91c1-984a683f0743.png)

**Comment by NPDebs** [comment]
Hello, lovelies!
Thanks for the work here. We will be closing this issue as we have completed our rebranding exercise.

All the best! 🌷
