### ISSUE TITLE
Design logo for "Masked Cohort", cohort 2 of OLS. 

### ISSUE THREAD

**Issue by yochannah** [open-life-science/branding#15]
Each OLS Cohort (group of mentored trainees) of OLS has a name. The cohorts are: 

1. Open Seeds
2. Masked Cohort
3. Perseverance (like the mars rover)
4. Kenaz ([a rune for openness](https://runesecrets.com/rune-meanings/kenaz))
5. Hope

➡️ ➡️ ➡️  **This issue is to suggest a logo for MASKED COHORT only.** 

## Image requirements: 

1. Square
2. Vector format (ideally SVG, but any other vector format is fine too).
3. Not too complex - needs to make sense even when it's a small icon. 

To participate - start by making sketches of your idea. Post a if it's on paper, or a screenshot if your earlier ideas are digital. Post your ideas in-thread - **there is no need to make a pull request for this task.**

Help each other and provide feedback on each others' designs.

**Comment by Lydiaofficial** [comment]
Hi, I am indicating interest in taking this task.

**Comment by Ososeomo** [comment]
Hi, I am interested in this task and working on it.

**Comment by Ososeomo** [comment]
Hi Lydia, I may have missed where this instruction was discussed, could you please indicate where that is stated. I've read through the instruction above and I didn't come across the "3 days notification". It's only stating to help each other and give feedback to each other .You can reach out to me on slack if needed or just point it out to me here. Thank you. 
@yochannah can this also be affirmed?

**Comment by Lydiaofficial** [comment]
That's alright

**Comment by Ososeomo** [comment]
I designed a sketch on my notepad and also digitally. For my notepad sketch, I suggested possible colors for the logo and made an adjustment to the mask in the digital sketch. I'll appreciate feedbacks. Thank you

![sketch 1](https://user-images.githubusercontent.com/114418888/194921068-78f416ab-af43-4c68-9b6a-9c5f5f6b4ac7.jpeg)
![Skecth 2](https://user-images.githubusercontent.com/114418888/194921162-a5702571-9c96-49c7-a454-a881c7764546.jpeg)

**Comment by jilaga** [comment]
OLS-2 was in 2020, the pandemic year and you cannot talk about the pandemic without talking about face masks and also open science has been a really huge help in battling Covid.
This is a great idea for the Masked cohort Logo.

**Comment by jessjaey** [comment]
@Ososeomo I reallly like this concept
gives off the message well💯🤌🤌

**Comment by Ososeomo** [comment]
Thank you for your feedbacks @jilaga and @jessjaey 👍

**Comment by Ronnie-Mercy** [comment]
I really like the representation you gave using the people behind the mask as it speaks well about when OLS-2 was established! good one! @Ososeomo

**Comment by yaa-chi** [comment]
> I designed a sketch on my notepad and also digitally. For my notepad sketch, I suggested possible colors for the logo and made an adjustment to the mask in the digital sketch. I'll appreciate feedbacks. Thank you
> 
> ![sketch 1](https://user-images.githubusercontent.com/114418888/194921068-78f416ab-af43-4c68-9b6a-9c5f5f6b4ac7.jpeg) ![Skecth 2](https://user-images.githubusercontent.com/114418888/194921162-a5702571-9c96-49c7-a454-a881c7764546.jpeg)

Wow, this is amazing Ososeomo! Love the concept!

But @yochannah I think, it'll be best for OLS to have a constant logo then every other cohort can have a sub-logo to represent the topic of that year.

Just like what @Ososeomo has created👌🏾

**Comment by Ososeomo** [comment]
@yaa-chi I totally agree with the sub-logo suggestion. Its a brilliant idea. Thank you also for your feedback.👍

**Comment by Bisola15** [comment]
> I designed a sketch on my notepad and also digitally. For my notepad sketch, I suggested possible colors for the logo and made an adjustment to the mask in the digital sketch. I'll appreciate feedbacks. Thank you
> 
> ![sketch 1](https://user-images.githubusercontent.com/114418888/194921068-78f416ab-af43-4c68-9b6a-9c5f5f6b4ac7.jpeg) ![Skecth 2](https://user-images.githubusercontent.com/114418888/194921162-a5702571-9c96-49c7-a454-a881c7764546.jpeg)

This is very well done. We really cannot ignore the impact covid had on everyone that year. Very nice concept brought to life 👏🏾

**Comment by Olakid645** [comment]
![MASKED COHORT](https://user-images.githubusercontent.com/108859811/195168520-77daa5ab-f84e-4908-b9aa-31f0616c34db.png)

I made this Design on Photoshop with an ideal creation of mine in which the Mask represent the prevention of Covid to the organization or firm, the left hand side icon represent Engineering while the right hand icon represents Science and these two icons are Masked behind the Mask icon.

I hope the concept will be of help to the community or will generate more ideas from my peers

**Comment by Ososeomo** [comment]
@Olakid645 I'm blown away. This is really great.

**Comment by Olakid645** [comment]
> @Olakid645 I'm blown away. This is really great.

Thanks @Ososeomo. I appreciate your comment. Let's see what our Mentor @yochannah perspective will be on this.

**Comment by Bisola15** [comment]
> ![MASKED COHORT](https://user-images.githubusercontent.com/108859811/195168520-77daa5ab-f84e-4908-b9aa-31f0616c34db.png)
> 
> I made this Design on Photoshop with an ideal creation of mine in which the Mask represent the prevention of Covid to the organization or firm, the left hand side icon represent Engineering while the right hand icon represents Science and these two icons are Masked behind the Mask icon.
> 
> I hope the concept will be of help to the community or will generate more ideas from my peers

Blew my mind!!. This looks amazing!! I can’t even.. but looking at the design it speaks more about OLS itself than the cohort. The engineering and science inside the mask.... What do you think?

**Comment by niyolynate** [comment]
![olpppp](https://user-images.githubusercontent.com/98440370/195584888-dd5652c2-ff2c-49aa-9ce1-670654b935d2.PNG)


![kkk](https://user-images.githubusercontent.com/98440370/195584824-5e40a19e-31b8-4977-8b05-73896d8d1237.png)

Using Canva i made this design first from the OLS logo then dressed a mask on it to be a masked Cohort, open life science is a mask of many packages including Mentorship, Love, Science, Motivation, Confidence in People with different abilities, all in one Organisation. 
so its capturing many qualities.

**Comment by Olakid645** [comment]
> > ![MASKED COHORT](https://user-images.githubusercontent.com/108859811/195168520-77daa5ab-f84e-4908-b9aa-31f0616c34db.png)
> > I made this Design on Photoshop with an ideal creation of mine in which the Mask represent the prevention of Covid to the organization or firm, the left hand side icon represent Engineering while the right hand icon represents Science and these two icons are Masked behind the Mask icon.
> > I hope the concept will be of help to the community or will generate more ideas from my peers
> 
> Blew my mind!!. This looks amazing!! I can’t even.. but looking at the design it speaks more about OLS itself than the cohort. The engineering and science inside the mask.... What do you think?

Thanks for the amazing feedback @Bisola15, I just wanted the masked cohort icon to have representation of the main idea. Suggestions are allowed as well.

**Comment by manuuelab** [comment]
Hey guys, so I've got some sketches for logo idea for Masked Cohort. I just kept my mind free and open, and these are what I could come up with. Both logos would need to be supported by text to clearly pass across the idea. Please let me know your thoughts on this @yochannah 
![IMG_1674](https://user-images.githubusercontent.com/115406817/195786786-1d1930e9-3ede-4ea2-a2ca-813234e77191.jpeg)

**Comment by Idowufaith-data** [comment]
> I designed a sketch on my notepad and also digitally. For my notepad sketch, I suggested possible colors for the logo and made an adjustment to the mask in the digital sketch. I'll appreciate feedbacks. Thank you
> 
> ![sketch 1](https://user-images.githubusercontent.com/114418888/194921068-78f416ab-af43-4c68-9b6a-9c5f5f6b4ac7.jpeg) ![Skecth 2](https://user-images.githubusercontent.com/114418888/194921162-a5702571-9c96-49c7-a454-a881c7764546.jpeg)

This looks really amazing and i think it interprets the "Masked cohort' concept effortlessly

**Comment by Preciousutos** [comment]
Hello. Here's my contribution in sketching a unique logo for Masked cohort. My approach in sketching this was first analysis the meaning of the individual words then combining both.
 Masked: Wearing a mask on all or part of the face. Conceal from view
 Cohort: a group of people with shared characteristics.
In my attempt to combining both meanings in one, I made the first sketch (blue sketch). This sketch was inspired by @Ososeomo sketch. I thought of simplifying the logo a bit, hence the other two sketches. Since a cohort involves a group of people with shared characteristics, I decided to show the characteristics of one person , the symbol of the mask and the mask elastic band. This shows a masked up person

![IMG_20221018_113151_336.jpg](https://user-images.githubusercontent.com/82149094/196407041-b5302c9b-240b-4656-9eb3-9c9ae9bd65d2.jpg)

![IMG_20221018_112113_20.jpg](https://user-images.githubusercontent.com/82149094/196405858-f2ef57c9-29f3-4241-9355-77d6d2d6cea0.jpg)

**Comment by iremide1022** [comment]
> ![MASKED COHORT](https://user-images.githubusercontent.com/108859811/195168520-77daa5ab-f84e-4908-b9aa-31f0616c34db.png)
> 
> I made this Design on Photoshop with an ideal creation of mine in which the Mask represent the prevention of Covid to the organization or firm, the left hand side icon represent Engineering while the right hand icon represents Science and these two icons are Masked behind the Mask icon.
> 
> I hope the concept will be of help to the community or will generate more ideas from my peers

@Olakid645 this is awesome 🥰
Do you think it would look any better if those ropes are removed ?

**Comment by yochannah** [comment]
Some quick comments 

- people + mask is a gorgeous combination, thanks to everyone who has been thinking and working on this! 🙌 
- mmm, the bluegreen colour is tasty and soothing. 
- For the logo from @Olakid645 with the three words engineering, masked, and science - gorgeous! If I was taking it to be used for things, I'd probably want the arrows removed. It works well in big, but logos need to also be readible when they're small, too. 
- @manuuelab - I love your conceptualisations here! What might they look like if they were converted into vectors? (p.s. the top one reminds me of ninjas 🥷 )
- @Preciousutos your sketches are simple and clear (this is a good thing in logos)! What would your next step be? 
- @niyolynate I like how you used the OLS logo to be the straps of the mask. Possibly this logo might be a bit complex if it was a small logo (say on the corner of the page or sticker), how could you simplfy it? 
- @Ososeomo wow, you have mad skillz when it comes to sketches! What might they look like in vector form? Your colour scheme sounds fun too, I'd love to see it.

**Comment by Olakid645** [comment]
> > ![MASKED COHORT](https://user-images.githubusercontent.com/108859811/195168520-77daa5ab-f84e-4908-b9aa-31f0616c34db.png)
> > I made this Design on Photoshop with an ideal creation of mine in which the Mask represent the prevention of Covid to the organization or firm, the left hand side icon represent Engineering while the right hand icon represents Science and these two icons are Masked behind the Mask icon.
> > I hope the concept will be of help to the community or will generate more ideas from my peers
> 
> @Olakid645 this is awesome smiling_face_with_three_hearts Do you think it would look any better if those ropes are removed ?

Thanks for the nice comment @iremide1022, I just gave your innovation some thought and it seems nice and will make the logo more  simple and precise.

**Comment by Olakid645** [comment]
> Some quick comments
> 
> * people + mask is a gorgeous combination, thanks to everyone who has been thinking and working on this! raised_hands
> * mmm, the bluegreen colour is tasty and soothing.
> * For the logo from @Olakid645 with the three words engineering, masked, and science - gorgeous! If I was taking it to be used for things, I'd probably want the arrows removed. It works well in big, but logos need to also be readible when they're small, too.
> * @manuuelab - I love your conceptualisations here! What might they look like if they were converted into vectors? (p.s. the top one reminds me of ninjas ninja )
> * @Preciousutos your sketches are simple and clear (this is a good thing in logos)! What would your next step be?
> * @niyolynate I like how you used the OLS logo to be the straps of the mask. Possibly this logo might be a bit complex if it was a small logo (say on the corner of the page or sticker), how could you simplfy it?
> * @Ososeomo wow, you have mad skillz when it comes to sketches! What might they look like in vector form? Your colour scheme sounds fun too, I'd love to see it.

It was a pleasure that @yochannah recognized different ideas brought to life by my peers and I. In accordance to her review on my design and the innovation raised by @iremide1022 I worked on the logo and below is the result;

![MASKED COHORT](https://user-images.githubusercontent.com/108859811/196674528-bf9df225-ce95-4ac0-bc4d-f0a8368277b5.png)
![black-t-shirts-with-copy-space](https://user-images.githubusercontent.com/108859811/196674673-4b4e1afd-e845-4ee6-b9f7-2656146b1eb8.jpg)
![white-t-shirts-with-copy-space-gray-background](https://user-images.githubusercontent.com/108859811/196674683-11f55251-29a5-456c-b1c0-844097859073.jpg)

My reason for the T-Shirt mock-up is to give an answer and clear example to @yochannah idea on how well it will be readable irrespective of how small it might be. Reference to the front view of the Shirts.

Innovations are welcome as always

**Comment by Preciousutos** [comment]
@yochannah my next step is to design the sketches in a vector file and add colors. 
![Masked cohort](https://user-images.githubusercontent.com/82149094/197831875-bfff28ac-0f17-4050-8733-356e5a13c376.jpg)

**Comment by Mays26** [comment]
I decided to go in a different direction since it wasn't specifically stated that the mask had to do with covid. I decided to concentrate more on the cohort because it means a group or a team with a similar goal. @yochannah 
Here's my interpretation.
![Masked cohort](https://user-images.githubusercontent.com/116025692/197405084-3cc0d551-8808-4b4b-b316-0323b355d7b8.PNG)

**Comment by NPDebs** [comment]
All - thanks for your brilliant ideas! However, this issue has to be closed, as OLS has unmasked a new brand identity. 🎭
Know that your designs were nothing short of a masterpiece. ❤️
