### ISSUE TITLE
Design a logo for Kenaz, OLS's fourth cohort

### ISSUE THREAD

**Issue by yochannah** [open-life-science/branding#17]
Each OLS Cohort (group of mentored trainees) of OLS has a name. The cohorts are: 

1. Open Seeds
2. Masked Cohort
3. Perseverance (like the mars rover)
4. Kenaz ([a rune for openness](https://runesecrets.com/rune-meanings/kenaz))
5. Hope

➡️ ➡️ ➡️  **This issue is to suggest a logo for Kenaz only.** 

## Image requirements: 

1. Square
2. Vector format (ideally SVG, but any other vector format is fine too).
3. Not too complex - needs to make sense even when it's a small icon. 

To participate - start by making sketches of your idea. Post a if it's on paper, or a screenshot if your earlier ideas are digital. Post your ideas in-thread - **there is no need to make a pull request for this task.**

Help each other and provide feedback on each others' designs.

**Comment by oneboyfromife** [comment]
I'd love to work on this

**Comment by jilaga** [comment]
Kenaz is one of the rune symbols and I depicted the symbol with molecular components because it's open science. 
thoughts? 
<img width="2671" alt="Kenaz sketch" src="https://user-images.githubusercontent.com/105386444/194929424-9362dccc-bc3e-460b-b9b4-53ee607575d7.png">

**Comment by jessjaey** [comment]
I love "B" @jilaga 
✨✨

**Comment by oneboyfromife** [comment]
![20221010_200859.jpg](https://user-images.githubusercontent.com/105000665/194937011-7db59e92-3d43-4068-b95d-a75b1effafd8.jpg)
Kenaz is a rune symbol which means perseverance, controlled fire and  torch. I coined the logo out of the meaning of "Kenaz"

**Comment by jessjaey** [comment]
For the "Kenaz" cohort,
Kenaz has alot of meaning 
In hebrew, it means "Bright"
In rune meaning, it means "Torch, torchlight", a source of heat or light, it represents inner fire
In numerology orgin, it means someone very successful when it comes to education.
![image](https://user-images.githubusercontent.com/105664383/194938453-dbdfea5e-c6fa-4cf7-930f-9aa42f55b503.jpeg)
I tried to represent the inner fire of the students in this cohort.

**Comment by AdeolaAdekoya** [comment]
@jilaga I like your spin on it. I'm steering more towards b

**Comment by AdeolaAdekoya** [comment]
I decided to give this a try. I was inspired by the meaning of the rune Kenaz, which is meant to help one build self-confidence. It stands for the control and harnessing of fire for warmth and illumination.

The logo shows a human between a torch, using it as a guide to navigate obstacles

![IMG_1514](https://user-images.githubusercontent.com/86787740/194977093-5ed73427-0425-4557-a870-9a30805802d5.jpg)

![kenaz_torch_logo](https://user-images.githubusercontent.com/86787740/195110848-c48a0ab5-fc8f-4273-b809-289c5af1660e.svg)


Based on the feedback given, I decided to put the logo on a square background, so it could fit the requirements

**Comment by oneboyfromife** [comment]
Love the energy guys, but let's not forget the  requirements for the logo

**Comment by jilaga** [comment]
> @jilaga I like your spin on it. I'm steering more towards b

>> Thank you, I think I like B too

**Comment by jilaga** [comment]
> I love "B" @jilaga ✨✨

>> me too. lol

**Comment by niyolynate** [comment]
Ken
![skec](https://user-images.githubusercontent.com/98440370/195309277-b511438d-42b7-49f9-b19c-0ac8d74c7bbd.PNG)
![kenaz log](https://user-images.githubusercontent.com/98440370/195309424-5f5309a4-157b-41af-9a22-c37531b9cc24.png)

Kenaz ols fourth Cohort

**Comment by niyolynate** [comment]
Kenaz rune is associated with inspiration and creativity that is created in togetherness.


![koll](https://user-images.githubusercontent.com/98440370/195329986-e0ad0d79-d73a-4f9c-ba61-036644435445.PNG)

**Comment by niyolynate** [comment]
Kenaz logo sketch
![Capture](https://user-images.githubusercontent.com/98440370/195456780-d9e757ec-317a-45bb-8dd3-eb7f242073a7.PNG)


### Kenaz Logo for the forth cohort of the OLS
Since Kenaz Rune signifies awakening and growth it represents the brilliant flame of divine inspiration: 
"The fire in a person trying again, when we fail we rise again even if we are weak at first, we focus again to a fund Goal. "

Rebirth through sacrifice Creation through fire.


## Kenaz Logo for the forth cohort of the OLS

![koll](https://user-images.githubusercontent.com/98440370/195455944-36171c6c-4896-4a11-80f5-d25315814e98.PNG)
"Creation of courage in potential of every individual in our hope in what gifts we can embrace and have seen others succeed in." 

 Each  branch shows a strength that is connected in the root, with a common goal, we all can hold firm in one common identity and strength, with pride in one another holding Firm with confidence. Our objective will be worth a while in science and Technology as strong as that tree. which connects each branch, leaf and fruit. We can stand together with pride and strength in unity.

**Comment by kosonyemedaniella** [comment]
![Uploading 9E624700-A041-4584-BFC8-AC505EB11942.jpeg…]()

**Comment by kosonyemedaniella** [comment]
Kenaz means torch , illumination. My idea came from the brightest and natural source of light , the sun .

**Comment by kosonyemedaniella** [comment]
![image](https://user-images.githubusercontent.com/115454385/195535729-f948b54c-cbe5-4fcd-8549-eed2733e2e5a.png)

**Comment by manuuelab** [comment]
@yochannah and everyone, I loved working on these logo ideas, I hope either gets the chance to be vectorized. Since Kenaz means torch, intelligence, bright, I decided to depict that using a torch, fire, the brain/mind, books. The symbol on the torch on the bottom left logo stands for Fire in Hebrew so and Kenaz being a Hebrew word, made it feel like a good concept. Looking forward to feedback on these
![IMG_1669](https://user-images.githubusercontent.com/115406817/195788325-790e5e8b-efff-464e-b9ca-098cad287bc3.jpeg)

**Comment by niyolynate** [comment]
The Kenaz logo for the OLS'S Fourth Cohort
![Uploading koll.PNG…]()

**Comment by Preciousutos** [comment]
Kenaz: torch, fire, illumination.
In my research of Kenaz, I realized a lot is associated with it.
Kenaz symbolizes the control and harnessing of fire for warmth and illumination. It represents our having harnessed forces and energies greater than ourselves. Kenaz is like a torchlit library, and the energy is clearly filled with unlimited potential to learn and to map. 

So I made a few sketches to sum it all up. I used the torchlight & illumination approach, keeping the Kenaz symbol visible. Some of the sketches can serve as outlined and filled logos. One look at this, you know it's Kenaz Cohort. Simple and easy to understand

![IMG_20221018_130211_887.jpg](https://user-images.githubusercontent.com/82149094/196424775-8c9156a9-efb1-42ba-8403-2f3b0be461cd.jpg)

@yo Vector samples of the suggested Kenaz logo![kenaz cohort samples](https://user-images.githubusercontent.com/82149094/197503098-990c85c8-8a6f-4a9a-aeab-64c1fefeb58c.jpg)

**Comment by MargaretPearl** [comment]
@Preciousutos this is great. 

> Kenaz: torch, fire, illumination. In my research of Kenaz, I realized alot is associated with it. Kenaz is the symbolizes the control and harnessing of fire for warmth and illumination. It represents our having harnessed forces and energies greater than ourselves. Kenaz is like a torchlit library, and the energy is clearly filled with unlimited potential to learn and to map.
> 
> So I made a few sketches to sum it all. I used the touchlight & illumination approach, keeping the Kenaz symbol visible. Some of the sketches can serve as outlined and filled logos. One look at this, you know it's Kenaz Cohort. Simple and easy to understand
> 
> ![IMG_20221018_130211_887.jpg](https://user-images.githubusercontent.com/82149094/196424775-8c9156a9-efb1-42ba-8403-2f3b0be461cd.jpg)

I like the first one!

**Comment by yochannah** [comment]
Wow, all the creativity here around light, sources of fire, etc. is very inspiring. I'd love to see some of the sketches in vector format, too!

**Comment by ekjosh** [comment]
So, I came up with two concepts after exploring the Scandinavian (Norwegian) origin and use of the sharp edges and lines in their lettering.
![IMG_20221019_125513](https://user-images.githubusercontent.com/38887940/196684592-d2a85f05-8bae-42ae-96f4-f70e735f2994.jpg)

**Comment by ekjosh** [comment]
> Wow, all the creativity here around light, sources of fire, etc. is very inspiring. I'd love to see some of the sketches in vector format, too!

Hello, @yochannah 

Here is my submission for the logo design
![Kenaz-05](https://user-images.githubusercontent.com/38887940/196872926-634db975-3f81-4497-ac7f-755678bc3d0b.png)
![Kenaz-06](https://user-images.githubusercontent.com/38887940/196872929-d3b754ce-3748-42ec-a3b8-2954c3ad4e91.png)
![Kenaz-07](https://user-images.githubusercontent.com/38887940/196872930-59fd538d-f96d-4150-a2b0-39f7649e1187.png)

**Comment by Bisola15** [comment]
> @yochannah and everyone, I loved working on these logo ideas, I hope either gets the chance to be vectorized. Since Kenaz means torch, intelligence, bright, I decided to depict that using a torch, fire, the brain/mind, books. The symbol on the torch on the bottom left logo stands for Fire in Hebrew so and Kenaz being a Hebrew word, made it feel like a good concept. Looking forward to feedback on these ![IMG_1669](https://user-images.githubusercontent.com/115406817/195788325-790e5e8b-efff-464e-b9ca-098cad287bc3.jpeg)

Love the drawing.. The second one with the book does it for me. Welldone!!

**Comment by Bisola15** [comment]
> Kenaz: torch, fire, illumination. In my research of Kenaz, I realized alot is associated with it. Kenaz is the symbolizes the control and harnessing of fire for warmth and illumination. It represents our having harnessed forces and energies greater than ourselves. Kenaz is like a torchlit library, and the energy is clearly filled with unlimited potential to learn and to map.
> 
> So I made a few sketches to sum it all. I used the touchlight & illumination approach, keeping the Kenaz symbol visible. Some of the sketches can serve as outlined and filled logos. One look at this, you know it's Kenaz Cohort. Simple and easy to understand
> 
> ![IMG_20221018_130211_887.jpg](https://user-images.githubusercontent.com/82149094/196424775-8c9156a9-efb1-42ba-8403-2f3b0be461cd.jpg)

The first interpretation of it. I love it ! The way it seems like a torch is lighting up the symbol. I really like it

**Comment by Lisanna** [comment]
> Kenaz: torch, fire, illumination. In my research of Kenaz, I realized a lot is associated with it. Kenaz symbolizes the control and harnessing of fire for warmth and illumination. It represents our having harnessed forces and energies greater than ourselves. Kenaz is like a torchlit library, and the energy is clearly filled with unlimited potential to learn and to map.
> 
> So I made a few sketches to sum it all up. I used the torchlight & illumination approach, keeping the Kenaz symbol visible. Some of the sketches can serve as outlined and filled logos. One look at this, you know it's Kenaz Cohort. Simple and easy to understand
> 
> ![IMG_20221018_130211_887.jpg](https://user-images.githubusercontent.com/82149094/196424775-8c9156a9-efb1-42ba-8403-2f3b0be461cd.jpg)
> 
> @yo Vector samples of the suggested Kenaz logo![kenaz cohort samples](https://user-images.githubusercontent.com/82149094/197503098-990c85c8-8a6f-4a9a-aeab-64c1fefeb58c.jpg)

I also loved the first more than any other, but honestly all your proposals here are soooo good!

**Comment by jilaga** [comment]
> Kenaz is one of the rune symbols and I depicted the symbol with molecular components because it's open science. thoughts? <img alt="Kenaz sketch" width="2000" src="https://user-images.githubusercontent.com/105386444/194929424-9362dccc-bc3e-460b-b9b4-53ee607575d7.png">
B:
![Capture](https://user-images.githubusercontent.com/105386444/197841475-7818f74d-9efe-4e4d-9e5e-f3e676edbde4.JPG)
![sdfghjk](https://user-images.githubusercontent.com/105386444/197849572-3c86429e-6b3d-45f7-ace1-de37a7bf2bdd.JPG)

**Comment by stormztee** [comment]
Kenaz: torch, knowledge.

Key concepts: torch as a symbol of knowledge and intellect, searching for enlightenment, shedding light on matters, the quest for truth, skills and abilities, creativity, creativity, art, craftsmanship, acquisition and application of knowledge, intuition, enthusiasm in teaching/learning, kin-fire, opportunity, playfulness.

I decided to go with combinations of a torch and rising sun, bulb for my sketches. These are my takes on the kenaz cohort logo.
Sketches:
![photo_2022-10-28_17-13-34](https://user-images.githubusercontent.com/66218354/198746156-22b31741-0325-4417-9773-53d9786cbb40.jpg)
![photo_2022-10-28_17-13-31](https://user-images.githubusercontent.com/66218354/198746189-8bcaf498-02c0-4172-be05-8cb6f507f0df.jpg)
![photo_2022-10-28_17-13-24](https://user-images.githubusercontent.com/66218354/198746199-b249c5d9-0112-421c-83f0-9e191865438c.jpg)
Logos:
![photo_2022-10-28_17-49-23](https://user-images.githubusercontent.com/66218354/198746264-9c82ce66-999b-4add-97bf-b4d40bb36122.jpg)
![photo_2022-10-28_17-49-26](https://user-images.githubusercontent.com/66218354/198746273-903eaeaa-2a23-4160-80d5-c7061fca439b.jpg)
![photo_2022-10-28_17-49-16](https://user-images.githubusercontent.com/66218354/198746295-3ba5ecf6-a793-4ad9-8ad5-aa12bd42640a.jpg)

**Comment by Esyteck** [comment]
![Uploading 16673980184415126539265813350760.jpg…]()
I think a word logo will suit best

**Comment by Emmzybrown** [comment]
Hello guys, here are my own designs for this task... I would be grateful to have your feedback and possible suggestions on any improvement please. 

![IMG_20221103_170232_157](https://user-images.githubusercontent.com/85748210/199871991-007baf49-5de7-4285-8f3a-d30d1a2f022f.jpg)

![IMG_20221103_170241_576](https://user-images.githubusercontent.com/85748210/199872002-587d9096-cb61-4d20-aee2-3283c94c7ae3.jpg)

![IMG_20221103_170228_428](https://user-images.githubusercontent.com/85748210/199871980-504b1a69-c757-4b3b-9ae8-d2dbeb2de217.jpg)

![kenaz 1](https://user-images.githubusercontent.com/85748210/199872018-785abc19-61b7-4932-8fdf-8e8c65cfe9e0.svg)

![Kenaz 2](https://user-images.githubusercontent.com/85748210/199872020-112a21d4-b483-4837-95fa-c1fdd4c367af.svg)

![Kenaz 3](https://user-images.githubusercontent.com/85748210/199872025-3d86304a-a78b-42a0-b3aa-9a60ded2f631.png)

@yochannah

**Comment by NPDebs** [comment]
Hi hi! 😀
Thank you all for your valuable input! This issue is being closed as part of our rebranding efforts.
We encourage you to **keep shining your light**, lovely people! 🔥
