### ISSUE TITLE
Design a logo for Open Seeds, OLS's # cohort

### ISSUE THREAD

**Issue by MargaretPearl** [open-life-science/branding#24]
![seeds 1](https://user-images.githubusercontent.com/72576042/195118972-2af95983-42a7-4430-a7a9-7b5af6fc0786.png)

**Comment by MargaretPearl** [comment]
![ED11C8BF-6513-45A2-B225-9E8C2E99FE11](https://user-images.githubusercontent.com/72576042/195122176-b9f0fcfc-194a-4ac1-b614-910281056e80.png)

**Comment by MargaretPearl** [comment]
![ED11C8BF-6513-45A2-B225-9E8C2E99FE11](https://user-images.githubusercontent.com/72576042/195122250-0c66e3bc-219d-428c-ac6e-76d9056aee4d.png)

**Comment by lhurvedavies** [comment]
Hi Margaret, is there a set style guide (colour, font etc) for Open Seeds that must be adhered to for the logo design?

**Comment by AdeolaAdekoya** [comment]
> Hi Margaret, is there a set style guide (colour, font etc) for Open Seeds that must be adhered to for the logo design?

Hello @lhurvedavies  , not really the image just ought to be square, Vector format and Not too complex . they didn't specify what colors as they said sketch is allowed however,I like to adhere to OLS brand colors which you can find in the brand guidelines.

**Comment by Esyteck** [comment]
![Uploading 16656756097387224124580936705816.jpg…]()
I'm not too good with sketches and my camera isn't very great. But the real design is bound to be amazing

**Comment by MargaretPearl** [comment]
Hello Esyteck, the uploaded Image has no preview, do you want to attach it again and share with us. 
Thank you and cheers.

**Comment by jesmanto** [comment]
![Uploading 16673972561378138589133603819756.jpg…]()
The previous image I uploaded here had some issues so I thought I should try again

**Comment by Esyteck** [comment]
![16673978317278644596301751013538](https://user-images.githubusercontent.com/112022744/199509812-ff8c343f-40e0-4adf-bc86-383f45d30efb.jpg)
The image I previously uploaded here had some issues. Thanks for pointing that out @MargaretPearl

**Comment by MargaretPearl** [comment]
![Untitled-1](https://user-images.githubusercontent.com/72576042/199681698-0a1f286b-3cda-446b-ae92-820834c21e70.png)
![Untitled-2](https://user-images.githubusercontent.com/72576042/199681731-30c5bac1-9ad5-4558-a241-512891cfb06b.png)

**Comment by NPDebs** [comment]
Hi, Margaret Pearl. 👋
Congrats on creating your first ever GitHub issue, and thanks for sharing your creativity with us! 😍

Closing this issue, because OLS has taken on a new brand identity. You were fantastic regardless!

Stay beautiful. ❤️
