### ISSUE TITLE
Redesigning of open life science landing page

### ISSUE THREAD

**Issue by Esyteck** [open-life-science/branding#26]

**Comment by ekjosh** [comment]
I am interested in and would be absolutely delighted to work on this

**Comment by Esyteck** [comment]
Hi@yo I would love to work on this.

**Comment by ZeedDeveloper** [comment]
@Esyteck I would love to work on this task, can I be assigned to it, please

**Comment by Bharlikiss** [comment]
Hi @Esyteck i would love to be assigned this task

**Comment by Esyteck** [comment]
Hi @Bharlikiss, I think we should work together on this. What do you think?

**Comment by Bharlikiss** [comment]
Hello @Esyteck sure, that'll be great. What next

**Comment by Esyteck** [comment]
https://olsinternships.slack.com/files/U045JBYD2LE/F0474CAT4SZ/macbook_pro_16cool.png

**Comment by Esyteck** [comment]
Alright check out my mock up and see what we can modify. Suggest something or possibly come up with any idea then we look into it ok

**Comment by Bharlikiss** [comment]
> https://olsinternships.slack.com/files/U045JBYD2LE/F0474CAT4SZ/macbook_pro_16cool.png

the link isn't opening

**Comment by niyolynate** [comment]
I would also like to participate in this design.

**Comment by Bharlikiss** [comment]
Hi @Esyteck so here's my design suggestion and putting in mind that the mentors said we could only make suggestions as regards to the design but not the real deal as that will be the job of the Lucky intern selected. So i came up with a basic STYLEGUIDE and a WIREFRAME  of the landing page , so here's the link to the figma file. Reviews and suggestions are welcome

[<>](https://www.figma.com/file/0NSyoxqrF7SvtdhLVsVQfB/OLS-landing-page?node-id=7%3A43)

**Comment by NPDebs** [comment]
Hi all! 👋 This issue is being closed now, as OLS has finished its rebranding process.

Thank you all for your contributions here! 🌟
