### ISSUE TITLE
New Logo suggestion for open life science

### ISSUE THREAD

**Issue by Esyteck** [open-life-science/branding#27]
I have a new logo idea for Open Life Science
| Currrent Logo | 
| -------------- |
![logo](https://user-images.githubusercontent.com/112022744/195337324-ea02c877-c410-4a77-b73d-e780c27794c4.png) 

| Suggested Logo | 
| ---------------- |
![IMG-20221011-WA0046](https://user-images.githubusercontent.com/112022744/195337461-5e09bb86-082c-4315-949a-72f63b24e731.jpeg)

**Comment by Bisola15** [comment]
OMG! This is beautiful! 🥺🥺 Amazing! Well done
There's a but 🥲
So there's currently an issue opened to discuss a name change for the OLS. If there is a name change, a new brand identity will also be borne. which means the logo will be changed. I suppose for now this might not be done. However, the mentors can clarify on this. For faster response, you can also send a message on slack
@yochannah @bebatut

But this is beautiful

**Comment by Esyteck** [comment]
Thanks Bisola

**Comment by Esyteck** [comment]
Thanks dearest Bisola. We are designers. We are always ready to design
something new. No worries, once the decision is made, I'll design something
new to match the new brand. Thanks for appreciating my design though. It
meant a lot to me

**Comment by Bisola15** [comment]
Always ready to design dear!!! Yess!!! 💃🏾💃🏾

**Comment by latifatakin** [comment]
@Esyteck the design you came up with is really lovely 😳. Lovely is an understatement. I love that it depicts OLS perfectly and also in tone with the brand colors.

**Comment by Esyteck** [comment]
Glad you like it!

**Comment by iremide1022** [comment]
@Esyteck this is amazing

**Comment by Esyteck** [comment]
Glad you like it!

**Comment by NPDebs** [comment]
We like it too, Esyteck. 😁
Though the issue has to be closed now as part of rebranding efforts, this is certainly an invaluable piece of art. 😍 

Keep being a creative genius! 💪
