### ISSUE TITLE
Open life science Logo Illustration

### ISSUE THREAD

**Issue by Blessing1135** [open-life-science/branding#28]
I would like to add to this Project by contributing if Permitted.

**Comment by Bisola15** [comment]
Hi Blessing!! So there's currently an issue opened to discuss a name change for the OLS. If there is a name change, a new brand identity will also be borne. which means the logo will be changed. I suppose for now this might not be done. However, the mentors can clarify on this. For faster response, you can also send a message on slack

@yochannah @bebatut

**Comment by NPDebs** [comment]
Thank you, Blessing and Bisola! ❤️

Closing this issue now as part of rebranding efforts.
