### ISSUE TITLE
OLS Landing Page Redesign

### ISSUE THREAD

**Issue by latifatakin** [open-life-science/branding#29]
I went through the OLS landing page. I noticed some areas of improvement.

1) A search field on the website will make it easier for users to navigate the website.

2) Hero section with a call-to-action button. The hero section will be about the OLS mentorship program and a CTA button that will prompt the user to register for the next cohort.

3) A section that will explain what open science and OLS mean. Not all who visit the website know what the OLS community does. Users should be able to gain such knowledge on the website. This section will have a button that directs users to the About page. The about page

4) Social Proof: Testimonials from past mentees should be on the landing page. It helps build trust in the brand.

5) Call To Action button for users who might want to subscribe to the announcements list.

**Comment by latifatakin** [comment]
@yochannah I would like to work on this task

**Comment by Bisola15** [comment]
Hi @latifatakin I agree with all you mentioned up there. There is an issue opened to discuss how the site can be made better. Applicants had a call where we discussed these changes you raised in detail, however mentor @bebatut had clarified that those would be the job of the interns. 

The most we can do during this stage is suggest possible ways to make the website better and fix minor changes.

**Comment by Esyteck** [comment]
Oh wow! That's a cool clarity @Bisola

**Comment by latifatakin** [comment]
@Bisola15 Thanks for clarifying this 🌷

**Comment by ZeedDeveloper** [comment]
In addition to what @latifatakin has mentioned, I think the following will also look good on the website

 Clear grouping of information on the landing page into sections for quick access to the information a user might be needing 
 without having to read all the information on the landing page. I will like to suggest the following adjustments-

   1. An hero section that explains, at first contact the essence of OLS and what the organization does
   2. The OLS journey described in a story form on the homepage currently would be best in the about section which can also 
   be in the section on the landing page.
   4. Same goes for information on participants and all other information
   5. The footer also needs some reorganizing
   6. A call to action on each section
   7. Appropriate use of colors that will draws users in
   8. A Logo redesign

**Comment by latifatakin** [comment]
@ZeedDeveloper I agree with your suggestions. Landing page is the first page a new user will have contact with and therefore, it has to have sufficient information about OLS. 

Also, I went through the website again to check for further improvements. I think a search bar is needed so as to improve user experience. 
 A search bar will enable users to navigate the app faster.

**Comment by Bharlikiss** [comment]
@latifatakin @ZeedDeveloper @Esyteck Well said, i also noticed that the site needs a total modern arrangement like
1. The hero section could do with a more simplified header section with the particular page indicator being in form of a button
2. The Hero section could do with less text and more of a well explanatory image in form of slider carousels that will better depict the summary of OLS and a cal to action button
3. I think a full page should be dedicated to the about us for OLS , so as to create room for a proper explanation of the site, going through the site, it's a bit hard to know the values, goals and mission of OLS
4. The links in form of underlined words could do with a bit of touch-up rather than the words being underlined, we could have the links embedded and have the words with the primary color, different from the text colors generally used
5. The footer needs a total revamp, the  contents needs to be simplified, they are in clutters.

**Comment by latifatakin** [comment]
> @latifatakin @ZeedDeveloper @Esyteck Well said, i also noticed that the site needs a total modern arrangement like
> 
> 1. The hero section could do with a more simplified header section with the particular page indicator being in form of a button
> 2. The Hero section could do with less text and more of a well explanatory image in form of slider carousels that will better depict the summary of OLS and a cal to action button
> 3. I think a full page should be dedicated to the about us for OLS , so as to create room for a proper explanation of the site, going through the site, it's a bit hard to know the values, goals and mission of OLS
> 4. The links in form of underlined words could do with a bit of touch-up rather than the words being underlined, we could have the links embedded and have the words with the primary color, different from the text colors generally used
> 5. The footer needs a total revamp, the  contents needs to be simplified, they are in clutters.

@Bharlikiss Absolutely good points raised.

**Comment by Preciousutos** [comment]
> @latifatakin @ZeedDeveloper @Esyteck Well said, i also noticed that the site needs a total modern arrangement like
> 1. The hero section could do with a more simplified header section with the particular page indicator being in form of a button
> 2. The Hero section could do with less text and more of a well explanatory image in form of slider carousels that will better depict the summary of OLS and a cal to action button
> 3. I think a full page should be dedicated to the about us for OLS , so as to create room for a proper explanation of the site, going through the site, it's a bit hard to know the values, goals and mission of OLS
> 4. The links in form of underlined words could do with a bit of touch-up rather than the words being underlined, we could have the links embedded and have the words with the primary color, different from the text colors generally used
> 5. The footer needs a total revamp, the  contents needs to be simplified, they are in clutters.

In addition, information on the website is not properly arranged. I find it difficult to navigate to some pages. Alot of texts on the website and I think this can be worked on by adding relatable images. According to recent studies, the average person’s attention span is now only 7-8 seconds long. That means roughly eight seconds to grab your viewer’s attention and engage them enough to get your message across so they can take action. Images, videos, illustrations are attention grabbing, sending your viewers to where their attention is needed. The website has to be welcoming and friendly in respect to the OLS voice and values. Also, easy to navigate and comprehend for a better user experience. I also think OLS story, vision, mission, values should be visibly and visually stated. A little touch of a modern look will be perfect. Testimonials should be added

**Comment by Everythinglayemi** [comment]
> I went through the OLS landing page. I noticed some areas of improvement.
> 
> 1. A search field on the website will make it easier for users to navigate the website.
> 2. Hero section with a call-to-action button. The hero section will be about the OLS mentorship program and a CTA button that will prompt the user to register for the next cohort.
> 3. A section that will explain what open science and OLS mean. Not all who visit the website know what the OLS community does. Users should be able to gain such knowledge on the website. This section will have a button that directs users to the About page. The about page
> 4. Social Proof: Testimonials from past mentees should be on the landing page. It helps build trust in the brand.
> 5. Call To Action button for users who might want to subscribe to the announcements list.

@yochannah can I still work on this?

**Comment by niyolynate** [comment]
This is my fair sketch of the landing page
![landing](https://user-images.githubusercontent.com/98440370/198892294-e491bc01-5b5d-4db2-979b-800c41be9bb4.PNG)

**Comment by NPDebs** [comment]
Lati, thank you for being so proactive! We appreciate everyone who offered clarifications here as well. 💪

This issue is now being closed due to our new brand identity.
We do recognise and value the work done here! Thank you!❤️
