### ISSUE TITLE
Make a square version of the logo

### ISSUE THREAD

**Issue by yochannah** [open-life-science/branding#3]
Logo files are available in the root of this repo - we need a square version so we can use it as a profile pic :) 

the image should be in png and also svg so we can edit it and use it as an avatar. 

## if you want to pick up this task

1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), or email yochannah@gmail.com <3

**Comment by jonhenshaw** [comment]
I'll take it!

Edit: All done! #5

**Comment by yochannah** [comment]
fixed by #5 ✨
