### ISSUE TITLE
To contribute to Re-brand OLS name and materials

### ISSUE THREAD

**Issue by Muyheeza-design** [open-life-science/branding#30]
Hello,

I would love to contribute to this project.

**Comment by Esyteck** [comment]
Hi@yo I would love to contribute to this project. Kindly approve

**Comment by ricMbugua** [comment]
Hi is there anyone working on this issue?

**Comment by Ismael-KG** [comment]
Just linking to issue #19, which might have some useful thoughts on this topic.

**Comment by latifatakin** [comment]
Hello @Muyheeza-design ,an issue #19 is open already for OLS name rebranding. 

@yochannah mentioned that everyone is welcome to contribute on the issue.

**Comment by iremide1022** [comment]
@latifatakin very true this issue has been opened for contributions before

**Comment by Braide1995** [comment]
Hi, I would love to contribute to this issue

**Comment by Ismael-KG** [comment]
Just closing this issue as you are all welcome to contribute to #19 😊
