### ISSUE TITLE
design graphics to illustrate core OLS concepts. 

### ISSUE THREAD

**Issue by yochannah** [open-life-science/branding#45]
One of the core concepts of OLS is that by consciously and intentionally designing open behaviours into our work, we're more likely to be able to be effective. 

Currently we use these slides: https://docs.google.com/presentation/d/1fXnQvrt0uBXrYwUlvePSx6N7m7DnKLD1hCRTxos-QOk/edit#slide=id.p16 

see slides 3, 7, 16, 18, 19
--

multiple people can make prs on this issues

**Comment by Preciousutos** [comment]
Hi @yochannah . Are we to redesign just the slides noted or the entire presentation?

**Comment by jilaga** [comment]
@yochannah could you explain further on what you mean by graphics? Like poster designs?

**Comment by yochannah** [comment]
great questions! 

@Preciousutos  The slides here are to illustrate concepts - but think of making a graphic, rather than just the slide. Something we can re-use everywhere that illustrates the concept. 

@jilaga yes, but probably not as big. Try to aim for things that would still _fit_ onto a slide, or a webpage. They can be more complex than a logo, though!

**Comment by Bisola15** [comment]
Thank you @yochannah ❤️

**Comment by jilaga** [comment]
Okay @yochannah. Should we use the current branding guide or can we stretch a little bit away from it?

**Comment by stormztee** [comment]
Hello @yochannah . Should we stick to the exact same copy that's already on the slides?

**Comment by Preciousutos** [comment]
@yochannah I noticed some typo and punctuation errors on some of the slides for example, slide 12 had a period after 'lessons' instead of a comma and slide 13 should be read through

**Comment by yochannah** [comment]
@jilaga go wild, use your creativity! 

@stormztee little tweaks are okay, and creative interpretations. IF you're not sure, ask in Slack? 

@Preciousutos heheh, don't worry about it too much, but definitely don't replicate our oopsies!

**Comment by stormztee** [comment]
Alright @yochannah

**Comment by niyolynate** [comment]
Graphics to Illustrate Core OLS concepts.
Slide One
![pre 1](https://user-images.githubusercontent.com/98440370/199381782-a2d845c4-0530-4ad8-867c-531929a52613.PNG)
 2
![pre2](https://user-images.githubusercontent.com/98440370/199381937-1d531ec4-05fe-4b12-b2bf-b6b470cdae51.PNG)
3
![pre 3u](https://user-images.githubusercontent.com/98440370/199381996-46b8ef05-a847-4e2b-b3c3-552d6067dc62.PNG)
4
 ![pre 6](https://user-images.githubusercontent.com/98440370/199382280-c77ea573-4bec-4c9f-bb48-c1a61396fa05.PNG)
5
![pre 8](https://user-images.githubusercontent.com/98440370/199382494-5d93a93d-d03a-4d2c-bed9-d2c18005736e.PNG)

**Comment by Blessing1135** [comment]
Alright @yochannah

**Comment by jilaga** [comment]
@Ismael-KG @yochannah here are some redesign ideas I came up with for the pages highlighted above. Feedback would be appreciated, thanks. 
<img width="960" alt="Slide 4_3 - 1" src="https://user-images.githubusercontent.com/105386444/198546988-af203eeb-f5da-4eba-a382-84e091f5bec3.png">
<img width="960" alt="Slide 4_3 - 3" src="https://user-images.githubusercontent.com/105386444/198546998-6b1cd8d4-3544-48c3-9c22-cfabaa2d86b9.png">
<img width="960" alt="Slide 4_3 - 4" src="https://user-images.githubusercontent.com/105386444/198547006-c7575543-0fb1-4c54-a478-63a90cd58df0.png">
<img width="960" alt="Slide 4_3 - 5" src="https://user-images.githubusercontent.com/105386444/198547015-d6b8979b-8a2b-4f03-b86b-696df6c22905.png">
<img width="960" alt="Slide 4_3 - 6" src="https://user-images.githubusercontent.com/105386444/198547037-1c14acb7-67e4-4765-bb7b-fe6dfee0d083.png">

**Comment by jilaga** [comment]
@yochannah I reread the description of this issue again and I am now a little confused, do we redesign the whole slides or just the numbers you highlighted?
Also I just realized that I should have made a pr instead 😬

**Comment by stormztee** [comment]
Hello, @yochannah @Ismael-KG. Here's my take on the redesign of the highlighted slides. Looking forward to your feedback; thanks.
![Slide 3 OLS](https://user-images.githubusercontent.com/66218354/198672394-f0a7d21e-4239-4e88-be34-045c81f68969.png)
![Slide 7](https://user-images.githubusercontent.com/66218354/198672421-96c8314b-d45b-4a82-b09b-8408a651000f.png)
![Slide 16](https://user-images.githubusercontent.com/66218354/198672462-e27097db-6a06-4117-a06f-6e7b61bc62d3.png)
![Slide 18](https://user-images.githubusercontent.com/66218354/198672500-d275faa6-ca0e-405e-9322-58365d26b0ee.png)
![Slide 19](https://user-images.githubusercontent.com/66218354/198672557-d69f4cd0-d9c0-4e9f-a613-3237854be0bd.png)

**Comment by AdeolaAdekoya** [comment]
@Ismael-KG @yochannah here are some graphics I came up with to illustrate the concepts in the slide. I look forward to the feedback.
![Slide nl16_9 - 25](https://user-images.githubusercontent.com/86787740/198858949-62d9c253-ae09-4463-be0d-2b2afea4437d.png)
![Slide 16_9 - 11](https://user-images.githubusercontent.com/86787740/198858951-de9cc96b-1b90-477c-b799-e9e1e90cd264.png)
![Slide 16_9 - 12](https://user-images.githubusercontent.com/86787740/198858952-ae638ff6-7e6b-4809-8a8b-b4a2ae065ac3.png)
![Slide 16_9 - 21](https://user-images.githubusercontent.com/86787740/198858954-960bbdd6-2b7d-4abd-8b3d-f784f05a989b.png)
![Slide 16_9 - 24](https://user-images.githubusercontent.com/86787740/198858955-05bc1183-2d96-44ba-8ef0-66eb42fec433.png)

**Comment by Ismael-KG** [comment]
So much great work! Just a few simple comments for each:
* @niyolynate, try to simplify the slides – for example, your third slide with the core values should be either the tree or the blurb on the left, but not both. Your use of trees is very creative, and I hope they become a feature somehow!
* @jilaga, it would have been nice to see some use of green. That said, your design is nice and simple, very slick.
* @stormztee, those are very clear slides! The green you use for text is different to the logo's, and it doesn't contrast well enough with the white background, which is needed for legibility (check [this site](https://contrast-ratio.com/#hsla%28200%2C0%25%2C7%25%2C.7%29-on-white)).
* @AdeolaAdekoya, your slides are also clear, and use green in a clever way: three different tints/tones and one of them (I think) being the same as the current logo. I would just ask that you check the [contrast rate(https://contrast-ratio.com/#hsla%28200%2C0%25%2C7%25%2C.7%29-on-white) is good enough so that the green-on-white text is easily legible.

**Comment by AdeolaAdekoya** [comment]
Thanks for the feedback @Ismael-KG .. Utilized the contrast checker and adjusted the text  to make it more legible. Here are the updates.
![sdww](https://user-images.githubusercontent.com/86787740/198873265-3e5c8957-3609-4dfc-a8a2-1cb13e338082.png)
![lkkf](https://user-images.githubusercontent.com/86787740/198873266-4b90963c-9083-4f42-92ac-c3cf12c89236.png)

**Comment by AdeolaAdekoya** [comment]
This is a very useful too @Ismael-KG will definitely be using it in the future. Thank you☺

**Comment by niyolynate** [comment]
Design for the OLS Core Illustration.
![sav](https://user-images.githubusercontent.com/98440370/199090358-59aa17ac-48b7-4d86-8799-12917098d805.PNG)
![savv](https://user-images.githubusercontent.com/98440370/199090587-9794bc8e-eba1-4a8f-a1ad-bc2c731e51b3.PNG)
![savvo](https://user-images.githubusercontent.com/98440370/199090932-83d51a58-9009-40b8-a794-243a3674ebcd.PNG)
![savol](https://user-images.githubusercontent.com/98440370/199091057-77f978a3-8822-4cf8-a432-06e7010441ec.PNG)
![sil](https://user-images.githubusercontent.com/98440370/199092626-5d21fbc9-a525-450f-b3d4-8524ec6cbcce.PNG)

**Comment by Bisola15** [comment]
Finally made it here!!! 
![Introducing OLS -3 (Dark mode)](https://user-images.githubusercontent.com/81020434/198924955-bc7138ad-8a09-41d6-9e4a-cc83392fa7ff.png)
![Introducing OLS -7 (Dark mode)](https://user-images.githubusercontent.com/81020434/198924986-02023f3e-0efe-403b-96be-b31fbe85f967.png)
![Introducing OLS -16 (Dark mode)](https://user-images.githubusercontent.com/81020434/198925027-e99f8afc-cf56-4418-a6a5-2e1b589c7925.png)
![Introducing OLS -18 (Dark mode)](https://user-images.githubusercontent.com/81020434/198925060-5d5046be-1cba-4cd0-8f9f-57346ac4d7eb.png)
![Introducing OLS -19 (Dark mode)](https://user-images.githubusercontent.com/81020434/198925078-69271a1b-b1f7-4c33-a1b1-aeb8135c4298.png)
@yochannah @Ismael-KG Here is one part of my submission for the redesign. Please review 🥺 
I went for this Dark Mode because I naturally lean towards light mode. For me it's easier on the eyes and make for good contrast too. But that is subjective
I have also employed the use of gradient to test our theory of gradient 🥺

**Comment by Bisola15** [comment]
@yochannah @Ismael-KG  Yes, It's me again. My second submission for consideration; the light mode 
![Introducing OLS -3 (Light mode)](https://user-images.githubusercontent.com/81020434/198925736-5fe094c2-b2a8-41b0-86a0-27df3755aeb7.png)
![Introducing OLS -7 (Light mode)](https://user-images.githubusercontent.com/81020434/198925745-e254a049-7e89-4899-8b0f-0c874f615694.png)
![Introducing OLS -16 (Light mode)](https://user-images.githubusercontent.com/81020434/198925764-fd73b661-5fc4-487f-bdb6-43e5de1e1658.png)
![Introducing OLS -18 (Light mode)](https://user-images.githubusercontent.com/81020434/198925774-d7100851-19e4-4138-a422-3ba678cd2af2.png)
![Introducing OLS -19 (Light mode)](https://user-images.githubusercontent.com/81020434/198925787-37f2f73c-ab54-4ce9-b1d9-e1e8569c95a0.png)
For the light mode, I'd use a different background gradient from the light mode. There is a contrast with hoe the logo appears, it is bigger on the dark mode than the light. Which is better?
The last slide is also quite different in arrangement. I had the two concept sketched down so I decided to put them separately on each mode. Which is better?

**Comment by Bisola15** [comment]
> Thanks for the feedback @Ismael-KG .. Utilized the contrast checker and adjusted the text to make it more legible. Here are the updates. ![sdww](https://user-images.githubusercontent.com/86787740/198873265-3e5c8957-3609-4dfc-a8a2-1cb13e338082.png) ![lkkf](https://user-images.githubusercontent.com/86787740/198873266-4b90963c-9083-4f42-92ac-c3cf12c89236.png)

Babes @AdeolaAdekoya I like this. It is quite refreshing and clean. Well done 😊😊

**Comment by Bisola15** [comment]
> Hello, @yochannah @Ismael-KG. Here's my take on the redesign of the highlighted slides. Looking forward to your feedback; thanks. ![Slide 3 OLS](https://user-images.githubusercontent.com/66218354/198672394-f0a7d21e-4239-4e88-be34-045c81f68969.png) ![Slide 7](https://user-images.githubusercontent.com/66218354/198672421-96c8314b-d45b-4a82-b09b-8408a651000f.png) ![Slide 16](https://user-images.githubusercontent.com/66218354/198672462-e27097db-6a06-4117-a06f-6e7b61bc62d3.png) ![Slide 18](https://user-images.githubusercontent.com/66218354/198672500-d275faa6-ca0e-405e-9322-58365d26b0ee.png) ![Slide 19](https://user-images.githubusercontent.com/66218354/198672557-d69f4cd0-d9c0-4e9f-a613-3237854be0bd.png)

Love the simplicity of the design 😍😍 Very clean too 🥺

**Comment by Bharlikiss** [comment]
Hi everyone,  @yochannah @Ismael-KG. Here's my take on the redesign of the highlighted slides. Looking forward to your reviews. Thank you
![1](https://user-images.githubusercontent.com/105221721/198944229-a6b64456-9015-4f4f-8fb7-a428640a2614.jpg)
![3](https://user-images.githubusercontent.com/105221721/198944252-fd3b4f84-822c-4923-82e9-7b619cb08926.jpg)
![7](https://user-images.githubusercontent.com/105221721/198944268-637acdef-9a2a-46f2-af37-2f87a7999476.jpg)
![16](https://user-images.githubusercontent.com/105221721/198944283-c8da4ed1-c1f5-47be-8555-8f88d5f7ad52.jpg)
![18](https://user-images.githubusercontent.com/105221721/198944302-f8f5fdcd-b26d-485c-b042-1edd107e3240.jpg)
![19](https://user-images.githubusercontent.com/105221721/198944314-45d8963a-38c4-49cd-bedd-f1f7a305d85e.jpg)

**Comment by jilaga** [comment]
> So much great work! Just a few simple comments for each:
> 
> * @niyolynate, try to simplify the slides – for example, your third slide with the core values should be either the tree or the blurb on the left, but not both. Your use of trees is very creative, and I hope they become a feature somehow!
> * @jilaga, it would have been nice to see some use of green. That said, your design is nice and simple, very slick.
> * @stormztee, those are very clear slides! The green you use for text is different to the logo's, and it doesn't contrast well enough with the white background, which is needed for legibility (check [this site](https://contrast-ratio.com/#hsla%28200%2C0%25%2C7%25%2C.7%29-on-white)).
> * @AdeolaAdekoya, your slides are also clear, and use green in a clever way: three different tints/tones and one of them (I think) being the same as the current logo. I would just ask that you check the [contrast rate(https://contrast-ratio.com/#hsla%28200%2C0%25%2C7%25%2C.7%29-on-white) is good enough so that the green-on-white text is easily legible.



> So much great work! Just a few simple comments for each:
> 
> * @niyolynate, try to simplify the slides – for example, your third slide with the core values should be either the tree or the blurb on the left, but not both. Your use of trees is very creative, and I hope they become a feature somehow!
> * @jilaga, it would have been nice to see some use of green. That said, your design is nice and simple, very slick.
> * @stormztee, those are very clear slides! The green you use for text is different to the logo's, and it doesn't contrast well enough with the white background, which is needed for legibility (check [this site](https://contrast-ratio.com/#hsla%28200%2C0%25%2C7%25%2C.7%29-on-white)).
> * @AdeolaAdekoya, your slides are also clear, and use green in a clever way: three different tints/tones and one of them (I think) being the same as the current logo. I would just ask that you check the [contrast rate(https://contrast-ratio.com/#hsla%28200%2C0%25%2C7%25%2C.7%29-on-white) is good enough so that the green-on-white text is easily legible.

Thank you @Ismael-KG I would take that to effect and adjust the design.
<img width="960" alt="Slide 4_3 - 7" src="https://user-images.githubusercontent.com/105386444/199110908-cb8a6e95-7b9c-4b4b-914b-4c9c2370c023.png">
<img width="960" alt="Slide 4_3 - 8" src="https://user-images.githubusercontent.com/105386444/199110917-c131f882-c176-49e3-9ff7-81686c4d2e7f.png">
<img width="960" alt="Slide 4_3 - 9" src="https://user-images.githubusercontent.com/105386444/199110921-78a30b7c-0826-48fa-ad8e-31089edecf8e.png">
<img width="960" alt="Slide 4_3 - 10" src="https://user-images.githubusercontent.com/105386444/199110926-de712986-068c-47a6-a236-1f5b718988ba.png">
<img width="960" alt="Slide 4_3 - 11" src="https://user-images.githubusercontent.com/105386444/199110929-81a40182-0f68-48e9-8f64-bdfe0dc77cb0.png">

**Comment by Ismael-KG** [comment]
Thanks to those who've made reviewed submissions! Just some comments on the completely new ones:
* @Bisola15 it's great to see both light and dark mode options! I'd be curious to hear why light mode slides should prevail – dark mode is definitely easier on the eyes! I just wanted to comment how the use of gradients (which looks great!) is clearer on the light than dark background. Was this on purpose or a result of the light/dark background?
* @Bharlikiss These are great! Very simple and clear. There's just a change in font size that can be a bit confusing to the audience as you change from slide to slide. And the last slide switches between black and green text too frequently. Switching to green to highlight words is really useful to focus one's attentions, but too much of it and it breaks up the text!

**Comment by Bharlikiss** [comment]
Thank you @Ismael-KG for the reviews. I have adjusted the font size and also reduced the highlighted words on the last slide to avoid the break. Here are the updates. 
![1](https://user-images.githubusercontent.com/105221721/198976173-8a2121c0-731e-4d9b-8e4d-400c387b460d.jpg)
![3](https://user-images.githubusercontent.com/105221721/198977157-704c03e8-b3b7-409f-9f6a-fdd135e98f54.jpg)
![7](https://user-images.githubusercontent.com/105221721/198976186-40737346-0cce-4802-be66-7b891c7bc4dd.jpg)
![16](https://user-images.githubusercontent.com/105221721/198976191-3e4c201a-0b63-48ad-a6be-9ce292061233.jpg)
![18](https://user-images.githubusercontent.com/105221721/198976193-4df504d0-0df5-4f15-90c4-3d955f51bac9.jpg)
![19](https://user-images.githubusercontent.com/105221721/198976539-c3348598-8479-4a63-8592-13d5464a00b6.jpg)

**Comment by Bisola15** [comment]
> Thanks to those who've made reviewed submissions! Just some comments on the completely new ones:
> 
> * @Bisola15 it's great to see both light and dark mode options! I'd be curious to hear why light mode slides should prevail – dark mode is definitely easier on the eyes! I just wanted to comment how the use of gradients (which looks great!) is clearer on the light than dark background. Was this on purpose or a result of the light/dark background?
> * @Bharlikiss These are great! Very simple and clear. There's just a change in font size that can be a bit confusing to the audience as you change from slide to slide. And the last slide switches between black and green text too frequently. Switching to green to highlight words is really useful to focus one's attentions, but too much of it and it breaks up the text!

Thank you so much for that comment @Ismael-KG 😊  Personally, I would go for dark mode. I had just done the light mode as an option to present what it looks like, I don’t think light mode should prevail 🙈 (Personal bias). So the gradient patterns are not the same for the both modes. I had tried my hands on two different patterns, and for the dark mode I reduced the opacity a lot so that it would blend finely with the green background. I may have overdone it a bit.

![Introducing OLS -4 (Dark mode)](https://user-images.githubusercontent.com/81020434/198992081-a475d8d6-7743-4234-a716-27e41d39cda5.png)

This what the background in the dark mode looks like with increased Opacity, Lemme know what you think @Ismael-KG

**Comment by niyolynate** [comment]
@Ismael-KG  Ok thanks for the comment. am going to try that

**Comment by Olakid645** [comment]
@Ismael-KG @yochannah here are my redesign ideas for the pages highlighted above. Feedback would be highly appreciated, thanks.
![3](https://user-images.githubusercontent.com/108859811/199079272-8305942d-64ec-4bd2-967b-056f2f504d2e.jpg)
![7](https://user-images.githubusercontent.com/108859811/199079305-de677aec-3734-40dd-ad69-c3214148842f.JPG)
![16](https://user-images.githubusercontent.com/108859811/199079323-4c4aa950-f3d0-4f6a-92be-ae3ee709a0ee.JPG)
![18](https://user-images.githubusercontent.com/108859811/199079342-bcd047d2-029a-42b4-a692-4a7e13f9fe10.JPG)
![19](https://user-images.githubusercontent.com/108859811/199079360-02959eb5-7bec-4366-98d9-7a63ec891adf.JPG)

**Comment by Emmzybrown** [comment]
I would really love to participate on this task, @yochannah

**Comment by AdeolaAdekoya** [comment]
> I would really love to participate on this task, @yochannah
> 
> 

Hi @Emmzybrown, yes you can. She stated earlier that multiple people can contribute.

**Comment by Ismael-KG** [comment]
Hey @Olakid645, thanks for your suggestions! Two comments:
* Are these meant to be different styles to choose from? The five slides are great but very unique.
* I think I can quite confidently say the last one is a bit too "corporate" in its colours and general theme. The first two seem most coherent with other things we see on the OLS brand 😊

**Comment by jilaga** [comment]
Hi all, I made some illustrations for the core concepts of OLS and they are referenced below. I would really love some feedback or suggestions on improvements if any, Thanks.

**Comment by Emmzybrown** [comment]
Hello guys, below are some illustrations I made for the core values of OLS. I would love to get some reviews and suggestions on any improvement please. 

![SLIDE 3](https://user-images.githubusercontent.com/85748210/199513992-2a4b5726-335e-4758-bf7d-1cde37eea501.png)

![SLIDE 7](https://user-images.githubusercontent.com/85748210/199514010-4625fcf6-cb01-486f-a122-d2aebea4827c.png)

![SLIDE 16](https://user-images.githubusercontent.com/85748210/199514032-f7479b9f-241e-43ba-84c2-b00f0824522d.png)

![SLIDE 18](https://user-images.githubusercontent.com/85748210/199514119-78c1050e-a9b9-4aaa-9913-f2e0034d604e.png)

![SLIDE 19](https://user-images.githubusercontent.com/85748210/199514134-8e1b022c-0499-4f0f-900e-8d40c1413a5d.png)

**Comment by Lydiaofficial** [comment]
![image](https://user-images.githubusercontent.com/17748526/199987005-a48e4a34-b3c6-406a-8f04-9ee0665af31b.png)
Redesigned the image on the intro slide of OLS.

i surrounded "Hello" with tons of life sciences to give a new person an idea of what the organization is about.

**Comment by Preciousutos** [comment]
I could only attempt 2slides

![20221104_165305_0000](https://user-images.githubusercontent.com/82149094/200019747-18a39dc8-1b49-4b6f-a281-c4829d1356fd.png)
![20221104_165221_0000](https://user-images.githubusercontent.com/82149094/200019763-236dc99d-7db5-47b4-823c-e1c73ca51741.png)

**Comment by AdeolaAdekoya** [comment]
> Hello guys, below are some illustrations I made for the core values of OLS. I would love to get some reviews and suggestions on any improvement please.
> 
> ![SLIDE 3](https://user-images.githubusercontent.com/85748210/199513992-2a4b5726-335e-4758-bf7d-1cde37eea501.png)
> 
> ![SLIDE 7](https://user-images.githubusercontent.com/85748210/199514010-4625fcf6-cb01-486f-a122-d2aebea4827c.png)
> 
> ![SLIDE 16](https://user-images.githubusercontent.com/85748210/199514032-f7479b9f-241e-43ba-84c2-b00f0824522d.png)
> 
> ![SLIDE 18](https://user-images.githubusercontent.com/85748210/199514119-78c1050e-a9b9-4aaa-9913-f2e0034d604e.png)
> 
> ![SLIDE 19](https://user-images.githubusercontent.com/85748210/199514134-8e1b022c-0499-4f0f-900e-8d40c1413a5d.png)

I really like this. welldone😊

**Comment by Bisola15** [comment]
> Hello guys, below are some illustrations I made for the core values of OLS. I would love to get some reviews and suggestions on any improvement please.
> 
> ![SLIDE 3](https://user-images.githubusercontent.com/85748210/199513992-2a4b5726-335e-4758-bf7d-1cde37eea501.png)
> 
> ![SLIDE 7](https://user-images.githubusercontent.com/85748210/199514010-4625fcf6-cb01-486f-a122-d2aebea4827c.png)
> 
> ![SLIDE 16](https://user-images.githubusercontent.com/85748210/199514032-f7479b9f-241e-43ba-84c2-b00f0824522d.png)
> 
> ![SLIDE 18](https://user-images.githubusercontent.com/85748210/199514119-78c1050e-a9b9-4aaa-9913-f2e0034d604e.png)
> 
> ![SLIDE 19](https://user-images.githubusercontent.com/85748210/199514134-8e1b022c-0499-4f0f-900e-8d40c1413a5d.png)

Hey @Emmzybrown This is a nice concept. The contrasts of the green texts though, what do you think about it? I think the white background works better than the green one for the contrast. What do you think?

**Comment by Bisola15** [comment]
> I could only attempt 2slides
> 
> ![20221104_165305_0000](https://user-images.githubusercontent.com/82149094/200019747-18a39dc8-1b49-4b6f-a281-c4829d1356fd.png) ![20221104_165221_0000](https://user-images.githubusercontent.com/82149094/200019763-236dc99d-7db5-47b4-823c-e1c73ca51741.png)

This is sweet!! 😍😍 I like the simplicity. Did you make the illustrations?

**Comment by Bisola15** [comment]
> ![image](https://user-images.githubusercontent.com/17748526/199987005-a48e4a34-b3c6-406a-8f04-9ee0665af31b.png) Redesigned the image on the intro slide of OLS.
> 
> i surrounded "Hello" with tons of life sciences to give a new person an idea of what the organization is about.


I like the colours and the way they blend with the black background 😍😍 and "POP" very nice tbh. Always a sucker for dark modes.

**Comment by Preciousutos** [comment]
> > I could only attempt 2slides
> > 
> > ![20221104_165305_0000](https://user-images.githubusercontent.com/82149094/200019747-18a39dc8-1b49-4b6f-a281-c4829d1356fd.png) ![20221104_165221_0000](https://user-images.githubusercontent.com/82149094/200019763-236dc99d-7db5-47b4-823c-e1c73ca51741.png)
> 
> This is sweet!! 😍😍 I like the simplicity. Did you make the illustrations?>

No I didn't. I downloaded and edited them

**Comment by NPDebs** [comment]
Hi lovely people. 👋 
Thanks for letting your creativity run wild!

We're sliding in to close this issue, as OLS has a new brand identity. Your involvement in the redesign is appreciated!
All the best! 🚀🎨
