### ISSUE TITLE
Nebula branding assets

### ISSUE THREAD

**Issue by iramosp** [open-life-science/branding#90]
- [x] Update flyers with logo and QR to Nebula url
- [x] YouTube thumbnail
- [x] Slide template
- [x] Website - We will focus on structure and content first, before design. See  issue open-life-science/open-life-science.github.io#841

**Comment by jilaga** [comment]
Hi @iramosp, do we have a wishlist of information we would like on the YouTube thumbnail? 😊

**Comment by iramosp** [comment]
I think basic info for each call includes:
* Module, eg. `Open Data` or `Open Tools`
* Session number, eg. `Session 1` 
* Title, eg. `Programming best practices`
* Presenter
* Date

**Comment by jilaga** [comment]
@iramosp Thanks, noted.

**Comment by jilaga** [comment]
**Review request on the following assets:**

- Are there any elements of the designs that you feel could be improved or refined?
- Are the designs in alignment with visual needs and concepts?

I had to redesign the flyer to accommodate Nebula's developing brand identity, so here goes;

1. Flyer design
[Nebula flyer-portrait](https://github.com/user-attachments/assets/ee2663ef-b7de-442c-b482-551ee89cd715)

2. Youtube thumbnail
[thumbnail-youtube](https://github.com/user-attachments/assets/6cd1a2c8-b7df-4da2-9910-65a4d2853357)
(like we did with the certificates, we would use Next gen extension on Inkscape to automate the content)

3. Web design
[Prototype](https://shorturl.at/AWto2)
(Design to development review with Debs on Friday)

4. Slide Template : work in progress

**Comment by iramosp** [comment]
Thanks @jilaga, the brand identity is coming together very nicely!

1. **Flyer** - Taking advantage of this redesign to better communicate the selling points of the program:
 - [ ] Add NASA TOPS logo
 - [ ] Change text in blue box to "Transform to Open Science. Skills and support for your research" (I tried to visualize this here: https://docs.google.com/presentation/d/1MO6QwUxLQAmjq14-8TIdRyNx9F6zNx8fe01G3uPh70w/edit#slide=id.p)
 - [ ] For consistency, use "NASA TOPS" instead of "Nasa Tops"
 - [ ] Lowercase "of" in "Ethos Of Open Science"
 - [ ] Replace "Training calls on open science" for "Interactive training calls" and "Interactive discussions" for "All career levels welcome"
 - [ ] Can we fit a more direct call to action? Something like: "Register now for our upcoming cohort! Open to participants worldwide"
 - [ ] The tilted orange elements feel distracting to me, especially since everything else is level. The circles in the background already bring dynamism, and I don't think it's necessary to add _more_, but if you'd like to keep some playfulness, maybe explore off-centered or asymmetrical arrangements with the orange elements. I only recommend avoiding the inclination.
 Let me know if this is starting to look too packed. 

2. **YT thumbnail**
- [ ] Also add NASA TOPS logo
- [ ] Clarify that the big white number refers to the session number
- [ ] Profile pictures probably not realistic to add for every presenter
- [ ] Same comment as above regarding the tilted elements (in this case, green date and session number)
- [ ] Can we also have this as an editable google slides file to make it easier for facilitators to edit?
btw I'd love to co-present with Simeon Biles 😁 

3. **Web design**
The deploy preview Debs has been working on looks great! I do anticipate tweaking the content for clearer phrasing, etc, but keeping the same design.

5. **Slide template**
* I see the brand identity is leaning towards a dark theme (eg. the certificate, flyer and YT thumbnail). I would prefer a (mostly) light theme for the slide template, which I think will be easier to adapt and reuse. I'm imagining something similar to the Open Seeds template, with white as the main background color, and maybe some accent elements and 1-2 colored layouts for highlights.

**Comment by jilaga** [comment]
The feedback is so detailed and helpful. Thanks @iramosp! —I'm glad the brand identity is shaping up well!

I'll revise the designs to accommodate all your feedback, I also like the idea of having a direct CTA on the flyer.

**Comment by yochannah** [comment]
>having a direct CTA on the flyer 
+1!

**Comment by jilaga** [comment]
😮‍💨😮‍💨 I didn’t co-design with Simeon Biles either but I checked the design feedback boxes.

1. Flyer redesign
[Nebula flyer-square](https://github.com/user-attachments/assets/4ab6f463-009a-435e-974e-701ad4da6fd5)

2. YT thumbnail 
[YT thumbnail](https://github.com/user-attachments/assets/6cd85cbd-5a23-4cf2-8f26-a0954a76aa84)

(I also made a .ppt for easy edits https://docs.google.com/presentation/d/1QrLKzxar_VQeJ92haYFxNONFTHrlZcPKhg_22ujKZhY/edit )

3. Web design
I Noticed more pages have been added to the sub site💪🏾💪🏾. 

4. Slide template 
I made both light and dark themed variations that could be used interchangeably or together. (I promise they can work together 🤲🏽🫣)

 https://docs.google.com/presentation/d/1y9vmsUCFIpU3tLNRE8w1yS8pf74EfaUOa9h9lZrd244/edit
 
 I also added some use cases that can be erased to get blank templates.

**Comment by iramosp** [comment]
Thank you @jilaga! These look amazing 😍 

Small request: could you make the YT ppt available for everyone to view?

**Comment by jilaga** [comment]
Glad you like them ☺️☺️☺️🚀

Also gave edit access to anyone.
