### ISSUE TITLE
Flyer feedback from governance committee

### ISSUE THREAD

**Issue by iramosp** [open-life-science/branding#91]
> Flyer feedback from the OLS governance committee: 
> * On the flyer, can you perhaps add that there's a NASA certification?
> * Also maybe enlarge the logos, they are very tiny.
> * Add a big "NASA Open Science skills training" badge! See: https://www.linkedin.com/posts/dont-use-this-code_openscience-nasa-skillstraining-activity-7240365312968179713-gYcn

We can try two things:

- [x] 1. Adjust the current version to enlarge the logos and change "NASA TOPS Curriculum" for "NASA Certification on:" (and keep the curriculum below as is). I think these are relatively small changes
- [x] 2. In addition, work on a 2nd flyer that highlights the NASA collaboration and certification, including the [golden badge](https://images.credly.com/images/d64b24d8-66f3-435a-bc76-2d70c26b0d67/image.png). I see this as a different flyer whose main intention is hyping the NASA collaboration, to go with social media posts. It could include only minimal info about the program (this would go in the post itself), but definitely a call to action (registration). 

@jilaga, what do you think? Please feel free to propose other ideas!

**Comment by SaranjeetKaur** [comment]
https://www.linkedin.com/posts/openlifesci_openscience-reproducibility-nasa-activity-7242953507564101633-ZToC - On this advertisement, I feel OLS can leverage the fact (and humbly brag) that the initial content of the 101 curriculum was created by x% OLS community members :see_no_evil: 

So something like: 

Do you want to work closely with those who created the initial version of NASA TOPS 101 curriculum?

Are you new to Open Science and want to work closely with experts? 

If yes, apply for our ... in collaboration with ...

Why us? We are proud to share that the initial content of this curriculum was developed by x% of our community members!

You also get a certification/badge from NASA!

Can't afford to pay? Don't let that stop you, we offer fee waivers too, so write to us!

**Comment by iramosp** [comment]
> leverage the fact (and humbly brag) that the initial content of the 101 curriculum was created by x% OLS community members

Yes, great idea! Thanks @SaranjeetKaur

**Comment by jilaga** [comment]
Having another flyer to celebrate the NASA collaboration would work best to avoid cognitive overload on the flyer. 👩🏽‍💻


Given the limited time we have before the cohort begins, We could keep the flyer and treat it as our main, comprehensive piece for both digital and print. We’ll make any necessary adjustments based on feedback, but overall, the flyer will serve as the go-to for all key information.

Additionally we can develop a series of quick targeted social media flyers and posts. Each one will highlight different aspects of the cohort like the: 

- NASA collaboration
- Curriculum details and offerings
- Cohort benefits (certification, networking, etc.)
- Fee waivers and financial support
(With a clear CTA on each flyer)

**Comment by iramosp** [comment]
>  a series of quick targeted social media flyers and posts
💯 

Can we start with the NASA collaboration and Cohort benefits? If possible, have these flyers ready to share this week.

**Comment by jilaga** [comment]
Definitely! Glad you like the idea. I would share some options by Tomorrow

**Comment by jilaga** [comment]
Here, I grouped the info into 3 parts: 
- OLS x NASA collab
- Cohort benefits
- CTA
It also showcases the golden badge, OLS, NASA-TOPS and Nebula logos. 
[Nebula collab flyer-square](https://github.com/user-attachments/assets/4a548c05-256a-45c7-bb09-d813061b07e6)

I would love to hear your thoughts.

**Comment by iramosp** [comment]
Thank you @jilaga for the quick turnaround!

I love the layout and placement of each block (NASA collab, benefits and CTA). As always, stylish use of color ✨ 

I left [feedback as annotations directly on the flyer here](https://docs.google.com/presentation/d/1MO6QwUxLQAmjq14-8TIdRyNx9F6zNx8fe01G3uPh70w/edit#slide=id.g3077d647332_0_0). The feedback is mostly to 1) reduce amount of text, and 2) polish the phrasing of benefits.

**Comment by jilaga** [comment]
Thank you too! 😊
Does this address the feeadback?
[Nebula collab flyer-square (reviewed)](https://github.com/user-attachments/assets/671d7e46-ce22-4071-87aa-4b3ccccb4eab)

**Comment by iramosp** [comment]
Yes! 
Left a few extra comments in the slides. Main point is to remove "www" from website link and check qr code (sorry I didn't notice this before!). Reminder to also remove it from the first flyer.

**Comment by jilaga** [comment]
Awesome! ...and the qrcode links. 
[Nebula collab flyer-square (reviewed2)](https://github.com/user-attachments/assets/d1130ea6-edbd-4c78-aeeb-81c4d9a352ed)

On the main flyer;
- I changed the positions of OLS and TOPS logos, and made them bigger. 
- Added the golden and swapped in the certification text like you suggested- and I think it works now!

[Nebula main flyer (reviewed)-square](https://github.com/user-attachments/assets/36adc8e6-9640-4fdb-80ea-a0386d910a0d)

**Comment by SaranjeetKaur** [comment]
> Awesome! ...and the qrcode links. [Nebula collab flyer-square (reviewed2)](https://github.com/user-attachments/assets/d1130ea6-edbd-4c78-aeeb-81c4d9a352ed)

This one really looks great! Well done!!

**Comment by iramosp** [comment]
😍 Both look fantastic!
Last request to upload these to the repo and drive, please.

Also, thanks @SaranjeetKaur for your comments, I'll use your wording along with the flyer in our next post.

I'll close this issue and open separate ones for other flyer ideas.

**Comment by jilaga** [comment]
Quick one Irene; (I would usually ask Debs this but not at the moment)- Do I go ahead and upload the flyers to the prints-and-digital/flyer folder on the repo or create a Nebula folder to house all the assets? 

Incase you are wondering why I have this dilemma, It is a constant battle with keeping the repo organized and making things accessible.

**Comment by jilaga** [comment]
> > Awesome! ...and the qrcode links. [Nebula collab flyer-square (reviewed2)](https://github.com/user-attachments/assets/d1130ea6-edbd-4c78-aeeb-81c4d9a352ed)
> 
> This one really looks great! Well done!!

Thank you!! 🙏

**Comment by iramosp** [comment]
@jilaga, sorry I missed the question on repo structure. I'm going to open a different issue for that one, as we might need input from Debs and Doaa.
