### ISSUE TITLE
Please upload presentation template here for others to use

### ISSUE THREAD

**Issue by malvikasharan** [open-life-science/branding#94]
I am looking to link the presentation template from GitHub but I can't find it.
@jilaga Can you please create a folder and update that here?

Here a copy to download: https://docs.google.com/presentation/d/1575V9FZXgQA5DXkGRKYiRHbdR5D_QZWWFdwpYST6NWI/edit?usp=sharing

**Comment by Camille-Gonzalez-VA** [comment]
Done!
